### ISSUE TITLE
Counter and toggle

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tyrrell-tools#1]
A few notes on these nodes:
Counter:
- How can I reset the counter back to zero?  Does the topic need a specific name? (tried Reset/1 and clear/1 without results)
- We need to add a preset value, so when it is triggered, the output will show the preset value
- The Counter should have four different inputs (topic based), as in all occasions the counter is triggered by a transition from 0 to 1:

CountUp:      0 -> 1 -> 0 -> 1 -> 0 -> 1= count value of 3

CountDown:  0 -> 1 -> 0 -> 1 -> 0 -> 1= count value of 0

Preset = 10   0 -> 1 = count value of 10

Reset             0 -> 1 = count value of 0

Toggle:
We need a topic based input to pass on adjustable numeric values:
TempSP: 21 SetBackTemp :16 and true = 21; 
TempSP: 21 SetBackTemp :16 and false = 16; 
However the TempSP can vary through the voting system and the SetBackTemp depending on the office's thermal capacity might need global adjustment.

**Comment by hardillb** [comment]
Counter updates are done, will look at toggle shortly

**Comment by davidoc85** [comment]
> Counter updates are done, will look at toggle shortly.

Any updates on this yet?

**Comment by hardillb** [comment]
Just getting back to this, should have it done this afternoon

**Comment by hardillb** [comment]
Updates merged

use a topic of "setOn" to set the On value and "setOff" for the off value

**Comment by davidoc85** [comment]
I ran "node-red google.json -v" as the toggle button had disappeared after the last update. The following error shows:

> 7 Nov 17:15:53 - [warn] [toggle] ReferenceError: Invalid left-hand side in assignment

 What could be wrong?

**Comment by hardillb** [comment]
That looks like a bug in the toggle node I fixed last week, make sure you have pulled the very latest version from github

**Comment by davidoc85** [comment]
If you check toggle.html is 13 days old as opposed to the others that are 8days old...  Maybe toggle did not update?

**Comment by hardillb** [comment]
But the fix for it that error was in the js file not the html file so that doesn't matter. I will double check things shortly

**Comment by hardillb** [comment]
I have double checked the code in the repo is the latest and has the fix for this. Double check that you only have 1 copy of this node installed.

**Comment by davidoc85** [comment]
ok tested the new version works with 
msg.topic=setOn to change on value
msg.topic=setOff to change off value.

Please update the info and then we can close this

**Comment by hardillb** [comment]
New versions checked in with docs updated
